services:
  opencloud:
    image: ghcr.io/podmania/opencloud:latest
    # set to host user id and gid
    # defaults to 1000:1000
    # user: 1001:1001
    container_name: opencloud
    ports:
      - 9200:9200
    volumes:   
      - ./config:/etc/opencloud
      - ./data:/var/lib/opencloud
      - /etc/localtime:/etc/localtime:ro # optional: use either TZ variable or localtime mapping, not both
    environment:
      # https://docs.opencloud.eu/docs/dev/server/services/web/environment-variables/
      - OC_URL=https://localhost:9200
      # Optional:
      # OC_INSECURE="true" # set to true if using self‑signed certificates
      # PROXY_HTTP_ADDR: 0.0.0.0:9200
      # OC_LOG_LEVEL: error # log level (error, warn, info, debug)
    restart: unless-stopped
