services:
  opencloud:
    image: ghcr.io/podmania/opencloud:latest
    # set to host user id and gid
    # defaults to 1000:1000
    # user: 1001:1001
    container_name: opencloud
    ports:
      - 9200:9200
    volumes:   
      - ./config:/etc/opencloud
      - ./data:/var/lib/opencloud
      - /etc/localtime:/etc/localtime:ro # optional: use either TZ variable or localtime mapping, not both
    environment:
      - ADDRESS=127.0.0.1
      - GROUP=opencloud
      - PORT=9200
      - STATE_DIR=/var/lib/opencloud
      - URL=https://localhost:9200
      - USER=opencloud
      - IDP_ASSET_PATH=/nix/store/ji5wfk3ba7b0vaw5w1946mjkajw8j43f-opencloud-idp-web-6.1.0/assets
      - OC_BASE_DATA_PATH=/var/lib/opencloud
      - OC_CONFIG_DIR=/etc/opencloud
      - OC_INSECURE=true
      - OC_URL=https://localhost:9200
      - PROXY_HTTP_ADDR=127.0.0.1:9200
      - WEB_ASSET_CORE_PATH=/nix/store/sbwy5jgs8drc8501spjw5wiparg8ydhi-opencloud-web-6.2.0
    restart: unless-stopped
